Feat/pseudo dhcp
EasyTier/EasyTier pull request #109
Opened 2024-05-12 08:30 UTC by m1m1sha

pseudo dhcp

2024-05-12 09:02 UTC, m1m1sha commented
必须等待 report_peers 的 3s 休眠，所以一般需要 3s 左右时间

2024-05-12 09:07 UTC, KKRainbow commented
> 必须等待 report_peers 的 3s 休眠，所以一般需要 3s 左右时间

倒也不是，peer 列表来源于 ospf route 文件里的算法，那个大概1s就能拿到完整的 peer 列表

2024-05-12 09:11 UTC, m1m1sha commented
> > 必须等待 report_peers 的 3s 休眠，所以一般需要 3s 左右时间
> 
> 倒也不是，peer 列表来源于 ospf route 文件里的算法，那个大概1s就能拿到完整的 peer 列表

我回家了再优化一下，网络环境差的话是不是无法一次性完成获取 peer 列表，如果是这样的话还是有可能会出现同一个ip的情况

2024-05-13 12:45 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                                for i in (0..addr.len() - 1).rev() {
还是保持只支持 /24 比较好。dhcp 也从 /24 里分，addr[0..2] 是不用动的，跟 route 里其他地址保持一致就好了。

如果 route 里没有其他地址，就默认用 10.0.0.1

2024-05-13 12:45 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +            tokio::spawn(async move {
下面这段最好能抽个函数出来

2024-05-13 12:45 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                global_ctx_c.config.set_ipv4(ipv4_addr);
现在似乎没有考虑 ip 冲突，我感觉这个函数可以持续运行，每隔 20s 去重新检查下，如果有 ip 冲突就重新配置下 ip

2024-05-13 13:02 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                global_ctx_c.config.set_ipv4(ipv4_addr);
但是相同 ip 连入是会报错的吧好像，是不是不会出现相同 ip 的情况，还是说目前只是本机相同 ip 会报错无法连接。

2024-05-13 13:38 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                global_ctx_c.config.set_ipv4(ipv4_addr);
如果有 ip 冲突感觉应该是在连接的时候去解决吧，如果组网时候 ip 发生变化有些程序会需要重新配置 ip 否则会无法正常组网的吧

2024-05-14 10:31 UTC, KKRainbow requested changes

2024-05-14 10:31 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    unique_ipv4.sort();
这个 sort 起到啥作用

2024-05-14 10:31 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        println!(
最好不要在内部 print，可以加个 global event，然后在 easytier_core.rs 里去 print event。
GUI 也能感知到这个 event

2024-05-14 10:31 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    #[cfg(target_os = "macos")]
如果之前的子网跟当前的不一样，还需要把之前的 remove 掉

2024-05-14 10:31 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                tokio::time::sleep(std::time::Duration::from_secs(20)).await;
可以随机 sleep 10-20，如果有冲突方便两个节点选到不同的 ip

2024-05-14 10:31 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        while !set
这里似乎应该跟 unique_ipv4 里的判断重复？

2024-05-14 10:31 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                if dhcp_ip.is_none() {
似乎漏了一个逻辑：如果当前的 dhcp ip 跟其他节点都不同，说明没有冲突，就没必要重新设置了

2024-05-14 14:00 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                    unique_ipv4.sort();
对已使用 ip 进行排序，等等能先获取地址比较靠前的 ip

2024-05-14 14:06 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                if dhcp_ip.is_none() {
这里是 dhcp_ip 在需要修改 ip 时是 none 的，不用修改就是有具体值的，然后这里就是判断是否是 none 是的话进入修改 ip 的逻辑分支

2024-05-16 12:15 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        todo!("dhcp ip conflict");
这里加 todo 会在 ip 冲突的时候 panic，我理解这里直接把 ip set 成空，然后 del_route 就行了，等下一轮重新分配

2024-05-16 12:15 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    ((rand::random::<u8>() + 1) as f32 / 25.6) + 10.0,
rand::thread_rng().gen_range(10..20);

2024-05-16 12:15 UTC, KKRainbow commented on easytier/src/instance/virtual_nic.rs
> +    pub async fn link_down(&self) -> Result<(), Error> {
换 ip 不需要 link down

2024-05-16 12:15 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        let ipv4 = route
这里可以 collect 成 set = HashSet<cidr::Ipv4Inet>, dhcp_ip 也可以声明成 Ipv4Inet，好处是：

1. 可以通过 set.contains(dhcp_ip) 判重。
2. 可以通过 set.iter().map(|inet| inet.network()) 将其转为 cidr，变成类似 10.0.0.0/24 的形式。然后 take 第一个元素就可以直接获取到 dhcp 的子网。
3. 在获取 dhcp ip 时，假设子网为 network = inet.network()。获取 ip 可以简化为 network.iter().filter(|ip| ip.address() != network.first_address() && ip.address() != network.last_address() && !set.contains(ip)).take(1)

相比拆分成 u8 数组，可以让代码更清晰点

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +            let default_ipv4_addr = Ipv4Addr::new(10, 0, 0, 0);
default 应该是 10.0.0.1 ？最后一位是不是写错了

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    if dhcp_ip.is_none() {
这段似乎应该在 list routes 前面，不然第一次 list 完要干等 500ms，这 500ms 似乎什么都不会改变

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        if i == 5 {
这里感觉应该是 i == 5 && unique_ipv4.is_empty() 的时候再加 default，不然选到 default ip 也无法跟其他节点通信

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                            unique_ipv4
这个 else 似乎不该存在，default ip 这里加的话会太早了。可能出现 ip 冲突的时候就选到 default 了。保留上面那一出 add default 应该就足够了

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    for net in unique_ipv4.iter().map(|inet| inet.network()) {
map 后可能需要 take(1)，每个 ip 生成的 network 应该都是一样的，没有必要重复的去搜 ip

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    let last_ip = if let Some(last_ip) = dhcp_ip {
这段等价于
let last_ip = dhcp_ip.map(|p| p.address());

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        #[cfg(target_os = "macos")]
这段应该出现在 nic_c.remove_ip 后面，route 要跟着 ip 一起删掉。
因为 route 是不会因为上面 if 分支的操作而自动被删掉的

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    if let Some(ip) = ipv4_addr {
感觉这段的逻辑应该是
if last_ip.is_some() {
remove_ip()
remove_route()
issue_event(dhcp confilct)
} else {
set_ip
add_ip
add_route
}

这样可以在 ip 冲突后等待一段时间重新选择 ip （因为此时另一端可能也发现冲突了）

2024-05-17 01:37 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                let sleep: u64 = rand::thread_rng().gen_range(10..20);
这里可以改短点，5-10应该也够了

2024-05-17 03:40 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +            let default_ipv4_addr = Ipv4Addr::new(10, 0, 0, 0);
这个 default 是作为已存在的 ip 插入的，就是在最后需要在默认网段时候插入 10.0.0.0 然后去获取 10.0.0.1

2024-05-17 03:42 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                    if dhcp_ip.is_none() {
嗯嗯，确实

2024-05-17 03:46 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                        if i == 5 {
这边是，在 dhcp_ip 是 none 的情况下到循环最后一次时，加入默认网段去获取，然后因为插入时机是在 list_routes 全部插入之后，所以应该是在 unique_ipv4 全部遍历完发现没有可用地址再是从默认网段去找的

2024-05-17 03:48 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                            unique_ipv4
上面那个是在，网络里面没有其他 ip 的情况下最后加入默认网段去寻找。
这个是在最后加入，应该也是遍历完 unique 之后才去用 默认网段寻找的吧

2024-05-17 03:49 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                    for net in unique_ipv4.iter().map(|inet| inet.network()) {
那如果是跨网段的比如：A: 10.1.1.1，B: 10.1.2.1，这样的话是不是应该重复去查找

2024-05-17 03:52 UTC, m1m1sha commented on easytier/src/instance/instance.rs
> +                        #[cfg(target_os = "macos")]
嗯嗯

2024-05-17 10:59 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    for net in unique_ipv4.iter().map(|inet| inet.network()) {
跨网段说明配的有问题，不用管

2024-05-17 10:59 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +            let default_ipv4_addr = Ipv4Addr::new(10, 0, 0, 0);
嗯嗯，那没问题

2024-05-17 11:00 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        if i == 5 {
不能跨网段的，如果满了就不分了

2024-05-17 11:00 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                            unique_ipv4
同上

2024-05-17 13:10 UTC, KKRainbow reviewed
其他没有问题了

2024-05-17 13:10 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    println!("last_ip: {:?}", last_ip);
print 需要删掉，可以换成 tracing::debug!

2024-05-17 13:10 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                    if i == 5 && unique_ipv4.is_empty() {
i == tries - 1 ?

2024-05-17 13:10 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                        if nic_c.add_ip(ip.address(), 24).await.is_err() {
if let Err(e) = xx {
可以打印下 error 是啥

2024-05-17 13:10 UTC, KKRainbow commented on easytier/src/instance/instance.rs
> +                // check every 10 ~ 20 seconds
注释可以去掉

2024-05-17 15:16 UTC, KKRainbow approved these changes

2024-05-17 15:16 UTC, merged