Add one-click shell script
EasyTier/EasyTier pull request #196
Opened 2024-07-27 07:48 UTC by Sunakier

Add one-click shell script and edit README.md, README_CN.md
I think this is a temporary script because there are many things that are uncertain about Easytier right now.
But it works now (((((

2024-07-27 16:13 UTC, KKRainbow requested changes
另外最好调整下控制台输出，把 Easytier 改成 EasyTier。

2024-07-27 16:13 UTC, KKRainbow commented on script/easytier.sh
> +  echo -e "\r\n${GREEN_COLOR}下载 Easytier $LATEST_VERSION ...${RES}"
Downloading

2024-07-27 16:13 UTC, KKRainbow commented on script/easytier.sh
> +
脚本开始的时候需要先检查是否有root 权限

2024-07-27 16:13 UTC, KKRainbow commented on script/easytier.sh
> +  ln -s $INSTALL_PATH/easytier-core /usr/bin/easytier-core
可以试试放到 /usr/sbin 目录，并且加上 sticky bit。
参考
https://blog.csdn.net/weixin_44368963/article/details/131067160

2024-07-27 16:13 UTC, KKRainbow commented on script/easytier.sh
> +  rm -rf $INSTALL_PATH /etc/systemd/system/easytier.service /usr/bin/easytier-core /usr/bin/easytier-cli
如果 INSTALL_PATH 里有其他文件，是不是会被一起干掉。有些危险，最好指定只删 easytier 相关的

2024-07-28 18:36 UTC, Sunakier commented
已修改

2024-08-01 15:34 UTC, KKRainbow commented
稍晚点的 release 版本我想稍微改变一下压缩包的命名格式，让它变的更有好点，这个脚本晚点 review

2024-08-01 15:57 UTC, Sunakier commented
确实感觉得改一下，你发release之后我再适配一下新的命名格式

2024-08-09 16:04 UTC, KKRainbow approved these changes

2024-08-09 16:04 UTC, merged